server:
  port: 8090

spring:
  application:
    name: beatbox-backend
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/beatbox-realm
          jwk-set-uri: http://localhost:8080/realms/beatbox-realm/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/beatbox-backend
    username: postgres
    password: tomi1992
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql

keycloak:
  auth-server-url: http://localhost:8080
  realm: beatbox-realm
  client:
    id: beatbox-backend
    secret: J0OvqmN1zgOzAe4ZET1kWdP1OYjMrSxt

app:
  upload:
    audioDir: C:/uploads/audio
  sync:
    keycloak-batch-size: 100
    db-batch-size: 25
