spring:
  application:
    name: beatbox-backend
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/beatbox-realm
          jwk-set-uri: http://localhost:8080/realms/beatbox-realm/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/beatbox-backend
    username: postgres
    password: tomi1992
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql

server:
  port: 8090

logging:
  level:
    org:
      springframework:
        security: debug

app:
  upload:
    audioDir: C:/uploads/audio
